default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogCS_development

  #username: blogCS
  #password:
  #host: localhost
  #port: 5432
  #min_messages: notice
test:
  <<: *default
  database: blogCS_test
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: blogCS_production
  username: blogCS
  password: <%= ENV['BLOGTEST_DATABASE_PASSWORD'] %>
